[build-system]
requires = ["setuptools>=61.0", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "FlopPITy"
dynamic = ["version"]
description = "normalising Flow exoPlanet Parameter Inference Toolkyt"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "Francisco Ardevol Martinez", email = "68873290+franciscoardevolmartinez@users.noreply.github.com" }
]
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "sbi",
    "scipy",
    "tqdm",
    "subprocess",
    "scikit-learn",
    "torch",
    "corner",
    "multiprocessing",
    "cloudpickle"
]

[tool.setuptools]
packages = ["floppity"]

[tool.setuptools_scm]
write_to = "floppity/version.py"
